name: build_boards

on:
  pull_request:

env:
  BUILDDIR: build
  ARTIFACT_OUTPUT_DIR
  PERSISTENT_DIR
  BUILD_DL_DIR
  BUILD_SSTATE_DIR
  BUILD_LAYERCACHE_DIR
  BUILD_ASSETS_DIR
  KAS_UID
  KAS_GID

jobs:
  prepare:
    runs-on: ubuntu-24.04
    outputs:
      artifact_path: ${{ steps.artifact_path.outputs.artifact_path }}
    steps:
      - name: Clean up
        run: rm -fR $BUILDDIR
      - uses: actions/checkout@v4
      - id: artifact_path
        name: create artifact output directory
        run: echo "artifact_path=${{ env.ARTIFACT_OUTPUT_DIR }}/$GITHUB_REPOSITORY/$GITHUB_WORKFLOW/$GITHUB_RUN_NUMBER-$GITHUB_RUN_ATTEMPT" >> $GITHUB_OUTPUT

  build:
    needs: [prepare]
    strategy:
      fail-fast: false
      matrix:
        board: [
          raspberrypi4,
          raspberrypi4-64,
          raspberrypi5,
        ]
        subpath: [.]

    runs-on: ubuntu-24.04
    container:
      # the container image needs to be effectively hardcoded, it seems.
      image: ghcr.io/theyoctojester/devcontainer-base-yoep:main
      volumes:
        - ${{ env.PERSISTENT_DIR }}/downloads:${{ env.BUILD_DL_DIR }}
        - ${{ env.PERSISTENT_DIR }}/sstate-cache:${{ env.BUILD_SSTATE_DIR }}
        - ${{ env.PERSISTENT_DIR }}/layers:${{ env.BUILD_LAYERCACHE_DIR }}
        - ${{ env.PERSISTENT_DIR }}/assets:${{ env.BUILD_ASSETS_DIR }}
      options: --user ${{ env.KAS_UID }}:${{ env.KAS_GID }}
    steps:
      - name: enter build dir and build
        env:
          DL_DIR: ${{ env.BUILD_DL_DIR}}
          SSTATE_DIR: ${{ env.BUILD_SSTATE_DIR}}
          KAS_REPO_REF_DIR: ${{ env.BUILD_LAYERCACHE_DIR}}
        run: >
          mkdir -p $BUILDDIR/${{ matrix.board }} &&
          cd $BUILDDIR/${{ matrix.board }} &&
          kas checkout ../../kas/${{ matrix.subpath }}/${{ matrix.board }}.yml &&
          if [ -f "${{ env.BUILD_ASSETS_DIR }}/site.conf" ]; then
          cp ${{ env.BUILD_ASSETS_DIR }}/site.conf build/conf/site.conf;
          fi &&
          kas build ../../kas/${{ matrix.subpath }}/${{ matrix.board }}.yml
      - name: find
        run: >
          find . -iname "*raspberrypi5.mender*"
      - uses: actions/upload-artifact@v4
        with:
          name: raspberrypi5.sdimg
          path: build/tmp/deploy/images/raspberrypi5/raspberrypi5.sdimg
      - uses: actions/upload-artifact@v4
        with:
          name: raspberrypi5.sdimg
          path: build/tmp/deploy/images/raspberrypi5/raspberrypi5.mender

  collect:
    needs: [prepare, build]
    runs-on: ubuntu-24.04
    steps:
      - name: collect artifacts
        env:
          ARTIFACT_PATH: ${{ needs.prepare.outputs.artifact_path }}
        run: ./ci/collect_artifacts.sh
