name: Push workflow
on:
  push:
    branches:
      - main
    tags:
  pull_request:
jobs:
  devcontainer-cache-build:
    uses: rcwbr/devcontainer-cache-build/.github/workflows/devcontainer-cache-build.yaml@0.8.0
    permissions:
      packages: write
  pre-commit:
    if: github.event_name == 'pull_request'
    uses: rcwbr/dockerfile-partials/.github/workflows/pre-commit.yaml@0.10.0
    needs: devcontainer-cache-build
    with:
      pre-commit-image: ${{ fromJSON(needs.devcontainer-cache-build.outputs.devcontainer-cache-image-all_configs).target.pre-commit.args.DEVCONTAINER_PRE_COMMIT_IMAGE }}
  build-board:
    runs-on: ubuntu-24.04
    # needs: devcontainer-cache-build TODO restore
    container:
      image: ghcr.io/rcwbr/meta-mender-community-devcontainer-pre-commit:raspberry-pi-5
      # image: ${{ fromJSON(needs.devcontainer-cache-build.outputs.devcontainer-cache-image-all_configs).target.pre-commit.args.DEVCONTAINER_PRE_COMMIT_IMAGE }} TODO restore
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
          cd ..
          kas build meta-mender-community/kas/raspberrypi5.yml
          find . -iname "*raspberrypi5.mender*"
          find . -iname "*raspberrypi5.sdimg*"
